### ISSUE TITLE
Too much stringification

### ISSUE THREAD

**Issue by Pistahh** [serayuzgur/weld#13]
In main.rs 

   Some(path) => configuration.load(&path.to_string()),   

the arg ends up passed to File::open, which takes a reference as an argument, so I think this could be simplified to just passing "path" to configuration.load. Similarly

   configuration.load(&"weld.json".to_string());

why not just

   configuration.load("weld.json") ?

**Comment by serayuzgur** [comment]
path is std::string::String, but hardcoded parts are &str. How can ı unify these ?

**Comment by Pistahh** [comment]
If you look at the definition of open: https://doc.rust-lang.org/std/fs/struct.File.html#method.open

"AsRef" means that the "open" function can take anything (string-like), that can be converted into a reference. This includes a String and an &str too.

In configuration.load(&path.to_string()):
1. in path.to_string the to_string converts path into a String, so I guess path itself is _not_ a String but a &str anyways. But if it is indeed a String, then why call to_string at all?
2. .. then due to the & it is passed as a reference...

**Comment by serayuzgur** [comment]
Thanks for the detailed description.
