### ISSUE TITLE
AccessControlAllowOrigin

### ISSUE THREAD

**Issue by lf94** [serayuzgur/weld#20]
Add the header AccessControlAllowOrigin::Any to src/service/mod.rs, in impl Service for RestService for the `response`. I did this to my local copy but don't feel like forking on GitHub and doing a PR for something so simple.

```
        let response = Response
          ::new()
          .with_header(AccessControlAllowOrigin::Any);
```

Do not forget to include the module at the top:

```
use hyper::header::AccessControlAllowOrigin;
```

**Comment by serayuzgur** [comment]
@lf94  Thanks for the issue. I think this is very important in terms of usability.
