### ISSUE TITLE
POST body querystring -> JSON conversion

### ISSUE THREAD

**Issue by lf94** [serayuzgur/weld#21]

**Comment by serayuzgur** [comment]
@lf94 Please correct me if I am wrong. You want to get query params to be mergrd with the body of the POST request. Is it true?

**Comment by lf94** [comment]
No - I want the query string to be converted to a json, to be stored in db.json.

It's ok, I've already done this too :) I have just made a fork and applying my local changes now. You can cherry pick them :smile:
