### ISSUE TITLE
Html API explorer

### ISSUE THREAD

**Issue by serayuzgur** [serayuzgur/weld#8]
Html API explorer to see what you are mocking.

**Comment by albe-rosado** [comment]
I wanna take over this if is cool with you

**Comment by serayuzgur** [comment]
It would be awesome.

**Comment by albe-rosado** [comment]
hey @serayuzgur   I'm working in the API explorer... What I'm doing is generating routes parsing the db.json file, is kinda fuzzy tho... I dunno the level of detail we want on that,  to clear out a little bit my confusion can you give an example showing how are you picturing the api explorer to look?  i will be using maud to generate a quick html template.

**Comment by serayuzgur** [comment]
Hi @albe-rosado, I will prepare a simple document for you to explain what I was thinking, then we can discuss.

**Comment by albe-rosado** [comment]
great!

**Comment by serayuzgur** [comment]
Hi @albe-rosado,  please take a look at the wiki doc. that I wrote [API Explorer](https://github.com/serayuzgur/weld/wiki/ApiExplorer). I tried to explain the goal of the Explorer. Let's discuss it together and find the best possible solution.

**Comment by albe-rosado** [comment]
A simpler version of this https://apiexplorer.nationbuilder.com/nationbuilder? I wanted to show an UI with routes(ie. 127.0.0.1:8080/posts/1 ...) generated dynamically from the db.json file. Ideally something a developer will use to have an idea of the structure of the api, and show the result of those queries as a json. something like https://apiexplorer.nationbuilder.com/nationbuilder. Is that cool?

**Comment by serayuzgur** [comment]
Hi @albe-rosado , It is agood start but one important note. Weld supports hierarchic queries at services for all operations (CRUD).  I think this must be usable from the Explorer also. You can list all variations etc. What do you think about this ? And one question, do you need my help to make weld support static assets (files) like a web server ? I think this kind of HTML/JS serving could be easier with  a approach like that.

**Comment by albe-rosado** [comment]
Well, I did create an extra route for the explorer, wanted to make that using as must Rust as I could, if we want something like the link I showed then we need to serve files with hyper, I could take care of that... I want to use Rust as much as I can...

**Comment by serayuzgur** [comment]
Serving files with hyper is the solution I was thinking. Please, go on and fell free to contact me.

**Comment by serayuzgur** [comment]
Hi @albe-rosado , is everything ok? Do you need any thing ?

**Comment by albe-rosado** [comment]
oh no, I have been busy these days, sorry man, let's see what I can do next week...

**Comment by serayuzgur** [comment]
I think this issue become orphan again.

**Comment by lf94** [comment]
I think seeing the API in the db.json is enough. Lets keep this tool very self contained and not over-reaching.
