### ISSUE TITLE
Provide Cargo.lock

### ISSUE THREAD

**Issue by onur** [serayuzgur/weld#9]
It is recommended to keep `Cargo.lock` for binary only crates¹. weld is already ignoring semver rules for it's own dependencies, providing a `Cargo.lock` will prevent further breaking changes between dependencies and weld.

¹: <http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries>

**Comment by serayuzgur** [comment]
First of all thanks for the feedback. It is an alpha for now. I will fix this as soon as I decide the dependencies for real and release a beta. So I am leaving this open for now. Please feel free to contribute. I am open for all kinds of suggestions and pull requests.
